# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-XPath
version:      1.00
version_from: 
installdirs:  site
requires:
    IO::String:                    0
    Pod::XML:                      0
    UNIVERSAL::require:            0
    XML::XPath:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
